### ISSUE TITLE
How to reproduce the result reported in the table?

### ISSUE THREAD

**Issue by shrshore** [stefan-it/nmt-en-vi#2]
Hi, I'm trying to reproduce the result reported in the table recently. And I can only achieve ~23 with my pipeline. I'm afraid there might be something wrong.
According to your readme.md and your claim here https://github.com/tensorflow/tensor2tensor/pull/611, I'm training the model with
```
t2t-trainer --data_dir=t2t_data --problems=translate_envi_iwslt32k --model=transformer --hparams_set=transformer_base_single_gpu --output_dir=t2t_output --max_train_steps=125000
```
I'm not sure whether you run the model with such hyparameters, because in your readme.md you used transformer_base hparams set.
By the way, I'm using the latest version of t2t(1.5.6), but I guess that the version won't influence a lot.

Thanks and looking forward to your reply!

**Comment by stefan-it** [comment]
@shrshore Could you solve the problem?
